jwt:
  public:
    key: classpath:keys/public.pem
  private:
    key: classpath:keys/private.pem
  expiresIn: 1800

admin-user:
  username: admin
  password: admin

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect